import os
import subprocess
import requests
from synaptic.config import settings
from rich.console import Console

console = Console()

class GitDeployer:
    """
    Automates the autonomous deployment of Synapticity missions directly to new GitHub repositories.
    """

    def __init__(self, mission_id: str):
        self.mission_id = mission_id
        # We always bind strictly to the localized output code directory
        self.target_dir = os.path.abspath(os.path.join(settings.WORKSPACE_PATH, mission_id, "output"))

    def deploy(self):
        """Executes the full pipeline: Git Init -> Commit -> GitHub Create -> Push"""
        if not os.path.exists(self.target_dir):
            console.print(f"[{'bold red'}FAIL{'/bold red'}] No codebase found at {self.target_dir}. Cannot deploy.")
            return

        if not settings.GITHUB_TOKEN or not settings.GITHUB_USER:
            console.print(f"[{'bold yellow'}WARN{'/bold yellow'}] GITHUB_TOKEN or GITHUB_USER missing in .env. Skipping remote deployment.")
            console.print("Mission codebase remains purely localized.")
            return

        console.print(f"[{'bold cyan'}DEPLOY{'/bold cyan'}] Initializing autonomous GitHub remote deployment...")
        
        # 1. Initialize Local Git
        try:
            self._run_cmd(["git", "init"])
            self._run_cmd(["git", "checkout", "-b", "main"])
            self._run_cmd(["git", "add", "."])
            
            # Check if there's actually anything to commit
            status = subprocess.run(["git", "status", "--porcelain"], cwd=self.target_dir, capture_output=True, text=True)
            if status.stdout.strip():
                self._run_cmd(["git", "commit", "-m", "Auto-generated by Synapticity SDLC"])
            else:
                console.print(f"[{'bold yellow'}WARN{'/bold yellow'}] Codebase is completely clean or empty. Nothing to deploy.")
                return

        except Exception as e:
            console.print(f"[{'bold red'}FAIL{'/bold red'}] Local git initialization failed: {e}")
            return

        # 2. Map and Construct Remote Repository
        repo_url = self._create_remote_repo()
        if not repo_url:
            return

        # 3. Synchronize Remote and Push
        try:
            # Drop old remote if exists 
            subprocess.run(["git", "remote", "remove", "origin"], cwd=self.target_dir, capture_output=True)
            
            self._run_cmd(["git", "remote", "add", "origin", repo_url])
            console.print(f"[{'bold cyan'}SYNC{'/bold cyan'}] Pushing payload to {repo_url} ...")
            self._run_cmd(["git", "push", "-u", "origin", "main", "--force"])
            console.print(f"[{'bold green'}SUCCESS{'/bold green'}] Code deployed perfectly to GitHub!")
            console.print(f"Repository URL: {repo_url.replace('.git', '')}")
            
        except Exception as e:
            console.print(f"[{'bold red'}FAIL{'/bold red'}] Autonomous sync mechanism failed: {e}")

    def _create_remote_repo(self) -> str:
        """Calls the precise GitHub v3 REST API to generate a new private project structure."""
        url = "https://api.github.com/user/repos"
        headers = {
            "Authorization": f"token {settings.GITHUB_TOKEN}",
            "Accept": "application/vnd.github.v3+json"
        }
        payload = {
            "name": self.mission_id,
            "description": "Autonomously generated by Synapticity Engine",
            "private": True,
            "auto_init": False
        }

        try:
            # First, test if it already exists
            check = requests.get(f"https://api.github.com/repos/{settings.GITHUB_USER}/{self.mission_id}", headers=headers)
            if check.status_code == 200:
                console.print(f"[{'bold yellow'}WARN{'/bold yellow'}] Repository already exists remotely. Syncing directly...")
                return f"https://{settings.GITHUB_USER}:{settings.GITHUB_TOKEN}@github.com/{settings.GITHUB_USER}/{self.mission_id}.git"

            # Otherwise create it natively
            console.print(f"[{'bold cyan'}API{'/bold cyan'}] Establishing new remote instance '{self.mission_id}'...")
            res = requests.post(url, headers=headers, json=payload, timeout=15)
            
            if res.status_code == 201:
                return f"https://{settings.GITHUB_USER}:{settings.GITHUB_TOKEN}@github.com/{settings.GITHUB_USER}/{self.mission_id}.git"
            else:
                console.print(f"[{'bold red'}ERROR{'/bold red'}] GitHub API rejected creation: {res.text}")
                return ""
        except Exception as e:
            console.print(f"[{'bold red'}FAIL{'/bold red'}] Network interception during API creation: {e}")
            return ""

    def _run_cmd(self, cmd: list):
        """Runs an isolated command immediately inside the artifact output directory."""
        res = subprocess.run(cmd, cwd=self.target_dir, capture_output=True, text=True)
        if res.returncode != 0:
            raise RuntimeError(f"Command {' '.join(cmd)} crashed with output: {res.stderr}")
